import numpy as np

MAX_VAL = 2049 

OUTPUT_FILE = "f16_lut.h"

with open(OUTPUT_FILE, "w") as f:
    f.write("/*\n")
    f.write(" * Automatically generated by script_for_lookup_f16.py.\n")
    f.write(" */\n\n")
    f.write(f"static const uint16_t f16_integer_lookup_table[{MAX_VAL + 1}] = {{\n")
    
    for i in range(MAX_VAL + 1):
        hex_val = np.float16(i).view(np.uint16)
        f.write(f"    /* {i:<4} */ 0x{hex_val:04x},\n")
        
    f.write("};\n")

print(f"Look-Up Table written in '{OUTPUT_FILE}'.")